### PR TITLE
Graph Tile Visualisation

### PR DESCRIPTION
**Pull request by alangerak**
Added a MVC model based visualizer to display a graph. It contains classes to be able to draw Vertices on screen as wel methods to determine where to draw the Vertices. It also contains a small example of how the view can be updated by adding listeners to the vertices.
As for now, it lacks the integration with the GUI.

### CODE REVIEW

**Comment by joswinter** [comment]
Looks good to me, if it is merged we can hook it up to the graph parser and mutation indicator

**Comment by rutgervandenberg** [comment]
There is a second main added in this pull request, you should remove that. 

_EdgeLine.java_
Constructor is 70 lines. Should split this. The cases of the if statement seem like good candidates to split off into seperate methods. 

<code>calculateYIntersection</code> is 40 lines long. Seems reasonable to split it.

_TileView.java_
private method <code>drawEdge</code> is not used

Constructor is missing javadoc.

The rest looks fine.

**Comment by albert-smit** [comment]
looks fine except for the points mentioned by rutger

**Comment by rutgervandenberg** [comment]
Looks good.

**Comment by jorenham** [comment]
Looks ok to me.

**Pull request merged**
