### PR TITLE
Parser

### PR DESCRIPTION
**Pull request by albert-smit**
simple parser for Newick files

### CODE REVIEW

**Comment by jorenham** [comment]
The parser actually is a factory. Since we employ the factory pattern (http://www.tutorialspoint.com/design_pattern/factory_pattern.htm) as design pattern, you should change the parser to a factory.

PhylogeneticTreeItem actually is a Model (a bean even), so you should change the name and perhaps the namespacing to match the MVC standards. 

Also don't forget we have to do TDD, so you should have committed the test first.

**Comment by albert-smit** [comment]
tests have been added, and Newickparser is now a factory, and builds no longer error

**Comment by rutgervandenberg** [comment]
You should prefer to program towards interface <code>List<></code>, instead of implementation <code>ArrayList<></code>. 

Also, this is not actually a factory. You're not providing instances of some implementation of an interface. In fact, the whole advantage of a factory does not exist here. You cannot add different implementations without breaking old code.

**Comment by jorenham** [comment]
Looks ok now

**Pull request merged**
