### PR TITLE
Graph filter optimization

### LINKED ISSUE #193: GraphContainer.setVisible is very inefficient
It loops over every visible sequence, and then loops over all of its segments. This means that if a segment is used in all sequences (which happens regularly), it is looped over once for each sequence. 

Could make this a breadth first search that discards branches that contain no visible sequences.

### PR DESCRIPTION
**Pull request by albert-smit**
optimized filtering in graph, now loops over all sequenceSegments once, fixes  #193

### CODE REVIEW

**Comment by jorenham** [comment]
Looks good :+1:

**Comment by joswinter** [comment]
Looks good.

**Comment by alangerak** [comment]
Looks good

**Comment by rutgervandenberg** [comment]
Looks good.

**Pull request merged**
