### PR TITLE
The great refactor

### PR DESCRIPTION
**Pull request by jorenham**
Also known as "the day we could see the sky again".

Controllers now have the ability to "shout", i.e. broadcasting a message with arguments. Any controller can listen for specific messages.

Fixes https://github.com/ProgrammingLife5/LifeTiles/issues/79 and https://github.com/ProgrammingLife5/LifeTiles/issues/86.

_Example:_

``` java
public class Foo() extends Controller {
    @Override
    public final void initialize(final URL location, final ResourceBundle resources) {
        listen(Bar.HELLO, (controller, args) -> {
            System.out.println("Bar said " + args[0]);
        });
    }
}

public class Bar() extends Controller {
    public static final String HELLO = "helloShout";

    @Override
    public final void initialize(final URL location, final ResourceBundle resources) {
        hello();
    }

    private void hello() {
        System.out.println("Hello!")
        shout(HELLO, "hi");
    }
}
```

When `Foo` is initialized nothing will print. However when `Bar` is initialized it will print _Hello!_ and consequently `Foo` will print _Bar said hi_.

### CODE REVIEW

**Comment by albert-smit** [comment]
looks good

**Comment by joswinter** [comment]
Looks good to me.

**Comment by alangerak** [comment]
Looks good

**Comment by rutgervandenberg** [comment]
In your version of controller each controller needs to manually update every other controller when something changes. This is very error-prone, and not particularly scalable as compared to the original Observer. It requires every controller to be changed if another controller is added at some point.

Also, where is the filtering functionality? As far as I can tell right now it is only possible to load an entirely new model from storage. There is no way to communicate which sequences are visible after filtering. 

Why is there both a static ControllerManager and a Controller containing register, getController etc? The controller class seems to just call methods from ControllerManager, having both is somewhat confusing. 

Why is there a traverser package? This tells us absolutely nothing. 
- We've still got two sequence packages. 
- Controller.java: 
  - Is generic, but is used without parameters in many places. 
  - static main, menu etc, why not make this an enum?
  - loadModel: Should make this abstract
- ControllerManager.java:
  - getController: IllegalArgumentException: should be "UnknowN controller."
- GraphController.java: 
  - unloadGraph: Should contain a call to repaint at some point. Otherwise people will assume the graph is still loaded.

I'm not sure why this refactor (the controller part anyways) is a good idea.

**Comment by albert-smit** [comment]
updated version still looks good

**Comment by rutgervandenberg** [comment]
Much better now. I've still got some small remarks though: 
- Controller.java: 
  - shout: listeners is a map, why are you looping over its elements to find the one you need? Just use get(message).
  - The static strings for shout messages should be stored as an enum in Controller, not in the specific implementations. Right now if a controller wishes to listen to a specific message they have to store it themselves. You've then got two (static) strings that need to be identical for the program to work.
- SequenceController.java: 
  - setVisible: using retainAll is semantically confusing since you don't actually want to modify the set. You should use sequences.values().containsAll() instead.
  - setVisible: Why are you copying the set? If it is required, at least explain this in the javadoc. Right now a user might believe that the set they provided to setVisible is the one that will be used, when instead a copy is used.

**Comment by joswinter** [comment]
Looks good after commits, can this be merged?

**Comment by alangerak** [comment]
Looks good, but are those asserts only to test the code at runtime? If not, they should be removed because they are disabled at runtime by default.

**Comment by rutgervandenberg** [comment]
- FileUtils.java
  - findByExtension: asserts are generally disabled during runtime. Can this not be a directory, depending on what the user selects? If so, you may want to change this.

The rest looks great.

**Pull request merged**
