### PR TITLE
Rewritten the unification algorithm to use bfs.

### PR DESCRIPTION
**Pull request by jorenham**
Can now load 100 sequences in under a second when mutations and empty segments are turned off. The trick was to adjust the algorithm to use breadth-first-search.

Deadline: 23:59 01-06-2015

### CODE REVIEW

**Comment by joswinter** [comment]
Looks good, works very fast.

**Comment by albert-smit** [comment]
looks good

**Comment by alangerak** [comment]
Seems indeed to be faster if the other things are set to off. I approve

**Comment by rutgervandenberg** [comment]
Looks good.

**Pull request merged**
