### PR TITLE
Improved GUI

### PR DESCRIPTION
**Pull request by jorenham**
Made the window style-less, custom window controls, custom fonts.

### CODE REVIEW

**Comment by jorenham** [comment]
The minimization functionality doesn't work on my OS (Ubuntu 14), please let me know whether it does on some other OS.

**Comment by joswinter** [comment]
Code looks good, you sometimes don't have a new line at the end of some files. I will try the minimization function.

**Comment by jorenham** [comment]
Strange, I too see the trailing newline warnings of Github, but the local files don't have them.

**Comment by joswinter** [comment]
GUI works on windows 8 OS. :)

**Pull request merged**
