### PR TITLE
Sequence filtering

### PR DESCRIPTION
**Pull request by jorenham**
Can now make sequences (in)visible. Only the underlined sequences are displayed.

### CODE REVIEW

**Comment by jorenham** [comment]
Currently has bad performance which could be solved by https://github.com/ProgrammingLife5/LifeTiles/issues/86.

**Comment by albert-smit** [comment]
looks good

**Comment by joswinter** [comment]
Looks good!

**Comment by alangerak** [comment]
Looks good

**Comment by rutgervandenberg** [comment]
Looks good after most recent commit.

**Pull request merged**
