### PR TITLE
Sequence view

### PR DESCRIPTION
**Pull request by jorenham**
Created the sequence view. Currently doesn't load in the data but uses dummy data.

### CODE REVIEW

**Comment by rutgervandenberg** [comment]
- SequenceController.jgetDummyData(): We can load actual data, or at the least have the interface to do so. Dummy data should be removed. 
- SequenceController.getSequences(): Redundant method. Prefer to grab the actual graph from the ViewController. Also I'm fairly certain this will not work as expected. GraphFactory.getGraph() gives you an empty graph, so SequenceGenerator will in turn create an empty list. Not entirely sure what you're trying to accomplish.
- SequenceController: Should be an observer (that can be) registered to observe ViewController so that it can be updated when needed. 
- SequenceColor: Is not actually related to the sequence data, so should be in view, not model. 
- Should add tests.

**Comment by joswinter** [comment]
Looks good, everything that needs to be improved is already mentioned.

**Comment by albert-smit** [comment]
looks good, but why all the extra whitespace in pom.xml

**Comment by alangerak** [comment]
seems good to me.

**Pull request merged**
