### PR TITLE
Removed hashmap from traversal and added performance print

### PR DESCRIPTION
**Pull request by joswinter**
Not a lot of changes, but traversing works again in finite time.

### CODE REVIEW

**Comment by albert-smit** [comment]
When i run this code it only loads the 2 strain dataset

**Comment by joswinter** [comment]
The traversals are fixed. That is a flaw in the visualization of the Graph, which is being fixed with bucketCache

**Comment by jorenham** [comment]
Looks alright, although I still think the your traverser structure needs a big refactor.

**Comment by joswinter** [comment]
Yeah, we should first try to make the traverser performance feasible if possible. After that we could refactor the structure.

**Comment by albert-smit** [comment]
if the code is more readable it will be easier to optimize

**Pull request merged**
