### PR TITLE
Basic Gene Annotation visualization

### PR DESCRIPTION
**Pull request by joswinter**
Sequence segments that are annotated have a purple stroke and a tooltip.

### CODE REVIEW

**Comment by albert-smit** [comment]
looks good but still has a lot of magic numbers, in the geneAnnotationParser

**Comment by jorenham** [comment]
:+1:

**Comment by alangerak** [comment]
Looks good

**Comment by rutgervandenberg** [comment]
Introduces a bunch of PMD/findbugs violations. You should either fix these or, if you can't reasonably fix them, suppress them and add a comment explaining why you can't fix them.

**Pull request merged**
