### PR TITLE
Removed hashmap from traversal and added performance print

### PR DESCRIPTION
**Pull request by joswinter**
Not a lot of changes, but traversing works again in finite time.

### CODE REVIEW

**Comment by rutgervandenberg** [comment]
So this is basically removing redundant code? Fine by me ^^

**Comment by alangerak** [comment]
Looks good

**Comment by jorenham** [comment]
This has my blessing

**Comment by rutgervandenberg** [comment]
Something went wrong here. Double commits all over the place, as well as a merge. It was fine before.

**Comment by albert-smit** [comment]
looked good before the merge commit

**Comment by joswinter** [comment]
Made a new pull request with the changes

**Pull request closed without merging**
