### PR TITLE
Make ViewController singleton threadsafe.

### LINKED ISSUE #80: Make ViewController thread-safe
`nl.tudelft.lifetiles.core.controller.ViewController` is not thread-safe but used in different JavaFX threads.

### PR DESCRIPTION
**Pull request by rutgervandenberg**
Fixes #80

### CODE REVIEW

**Comment by jorenham** [comment]
`instance` should be made `volatile`.

**Comment by rutgervandenberg** [comment]
Why?

**Comment by jorenham** [comment]
So one can be sure all readers of `instance` see its value after a write operation completes on it.

**Comment by rutgervandenberg** [comment]
Instance is only ever written to once. Synchronised ensures that once a call to getInstance is made, no other can start executing it before the first has completed. Therefore once a call is made, all subsequent calls will get the instance.

**Comment by jorenham** [comment]
Clearly you haven't heard about _Double-checked locking_. You should read about it (http://en.wikipedia.org/wiki/Double-checked_locking) and update the code accordingly.

**Comment by rutgervandenberg** [comment]
That article actually mentions that the way I've implemented it is safe. I'm not using double check locking. 
It does mention that it is potentially inefficient, but since the method is not called very often that does not matter.

**Comment by alangerak** [comment]
I would not recommend double locking, better is to look at this post on stackoverflow referencing how to implement singleton with thread safety: (http://stackoverflow.com/questions/2008912/implementing-the-singleton-pattern-in-java/2008934#2008934)

**Pull request merged**
